services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    # Монтируем только папку с кодом,
    # чтобы не затирать alembic.ini и саму папку миграций,
    # но при этом видеть изменения в app/ при разработке:
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:8080"
    # НЕ монтируем node_modules!
    # Убираем bind-mount, чтобы не затирать
    # установленные зависимости сборки:
    # volumes:
    #   - ./frontend:/app

volumes:
  db_data:
