services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .                   # корень репо
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app             # для работы в dev-режиме

  frontend:
    build:
      context: .                   # корень репо
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app            # для живой подгрузки кода

volumes:
  db_data:
